### PR TITLE
Migrate to Ruff and update docs

### PR DESCRIPTION
**Pull request by EarlMilktea**
**Description of the change:**

Added badges:

- CI status
- codecov
- Ruff
- isort

### CODE REVIEW

**Comment by shinich1** [comment]
@EarlMilktea do we remove black and isort, now that we have Ruff? we can keep them as well.

**Review by shinich1 — APPROVED** [review]

**Comment by EarlMilktea** [comment]
I see. Let's migrate to Ruff!

**Comment by EarlMilktea** [comment]
MEMO: I didn't pin ruff version since it's still under active development.

**Comment by shinich1** [comment]
Is ruff's formatter stable? I am slightly worried about CI keep failing just because of ruff version difference.

**Comment by EarlMilktea** [comment]
There may be some breaking changes as it does not reach v1, but as it's designed to be compatible with black, black would also have similar breaking changes at that time.

I added these lines to `CONTRIBUTING.md` to ensure that contributors and CI use the latest version of Ruff.

```bash
# Be sure to use the latest version of ruff
pip install -U ruff
# Sort imports and format
ruff check --select I --fix .
ruff format .
```

**Comment by EarlMilktea** [comment]
And actually, in most cases, Ruff CI does not complain even if input codes are actually formatted by black/isort.

**Review by shinich1 — APPROVED** [review]

**Review by thierry-martinez — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
