### PR TITLE
Quantum Neural Network Demo

### LINKED ISSUE #46: [demo] Quantum neural network
Do [quantum neural networks](https://arxiv.org/pdf/1810.03787.pdf) (QNNs) work well with [LCMBQC](https://graphix.readthedocs.io/en/latest/lc-mbqc.html)? Please write up a python script or jupyter notebook in the `graphix/example` directory, describing the QNN algorithm with basic math, its implementation (both schematically and as a code), corresponding graph state before and after the Pauli measurement preprocessing. You may need to modify `graphix.transpiler.Circuit` class, or write a new transpiler class, to express the QNN circuit which may have non-equal number of input and output qubits. It would also be nice to see the plot of qubit resource (# of qubits in the resource state) vs QNN size, with and without Pauli measurement preprocessing.

Please see our [contribution guide](https://github.com/TeamGraphix/graphix/blob/master/CONTRIBUTING.md) before starting, and do not forget to comment on this issue to show your interest. We are always happy to answer questions, so do not hesitate to ask on this page.

Thank you for your interest, and good luck!

### PR DESCRIPTION
**Pull request by Gopal-Dahale**
## Context
Quantum neural network demo using Graphix. 

## Description of the change
In the Jupyter notebook, I have used the Data re-uploading quantum circuit from [this](https://quantum-journal.org/papers/q-2020-02-06-226/) paper to perform binary classification of circles dataset from sklearn. I have also added the qubit resource plot at the end.

## Related issue
Resolves #46

### CODE REVIEW

**Comment by shinich1** [comment]
@Gopal-Dahale I moved your code to a python file so that sphinx gallery can generate html. I hope this looks ok. 
I would appreciate if you could also add a little bit more explanations of the code, as in other examples. Thanks!

**Comment by Gopal-Dahale** [comment]
Sure will add some explanation

**Comment by Gopal-Dahale** [comment]
Can you share the tool you are using to convert it to a Python file? Can latex get converted successfully?

**Comment by Gopal-Dahale** [comment]
Hi @shinich1, I have made the necessary changes.

**Comment by shinich1** [comment]
@Gopal-Dahale could you comment on issue #46, so I can assign you to it? something like `@shinich1 please see #57` should be fine.

**Pull request merged**
