### PR TITLE
Fix Pauli measurement routine

### PR DESCRIPTION
**Pull request by shinich1**
Before submitting, please check the following:
- Make sure you have tests for the new code and that test passes (run `pytest`)
- format added code and tests by `black -l 120 <filename>`
- If applicable, add a line to the [unreleased] part of CHANGELOG.md, following [keep-a-changelog](https://keepachangelog.com/en/1.0.0/).
 
Then, please fill in below:

**Context (if applicable):**

**Description of the change:**
1. Fixed bug in `GraphState` graph state simulator, specifically, 
- `equivalent_graph_E2` method
- bug in toggling 'loop' in `s` method
- behaviour of `measure_x` and `measure_z` methods for isolated nodes
2. Fixed `measure` method of `StatevectorBackend`: 
- now we apply s and t signals by Clifford gate, not change of angles.
- effect of vops in `meas_op` is now done by application of Clifford gate conjugation on measurement operator, instead of interchanging of measurement axes 
3. Fixed pauli measurement preprocessing routine in `pattern.py`
- we treat the signals by applying Clifford gates, not by the change of angles

**Related issue:**
#62 
(#56)

also see that checks (github actions) pass.
If lint check keeps failing, try installing black==22.8.0 as behavior seems to vary across versions.

### CODE REVIEW

**Comment by masato-fuk** [comment]
@shinichi1 All changes appear to be good. By the way, I find `vop` makes the code a little complicated. As far as I understand, there shouldn't be any issues with merging vops into measurement angles and planes right after Pauli measurements(if my assumption is incorrect, please disregard this). I  believe it would be better to do so because simple structure let users follow up easily. But, I think this modification should be done in another issue...

**Comment by masato-fuk** [comment]
I'll fix a bug in flow finding algorithm, so please wait a moment.

**Comment by shinich1** [comment]
> By the way, I find `vop` makes the code a little complicated. As far as I understand, there shouldn't be any issues with merging vops into measurement angles and planes right after Pauli measurements(if my assumption is incorrect, please disregard this). I believe it would be better to do so because simple structure let users follow up easily. But, I think this modification should be done in another issue...

I agree, we will need to update angles as well as measurement planes, but that should be doable. I agree it would make things look much simpler.

**Comment by shinich1** [comment]
> I'll fix a bug in flow finding algorithm, so please wait a moment.

let's do this in a separate issue.

**Pull request merged**
