### PR TITLE
Support extraction of clusters from graph state

### PR DESCRIPTION
**Pull request by king-p3nguin**
Before submitting, please check the following:
- Make sure you have tests for the new code and that test passes (run `tox`)
- format added code by `black -l 120 <filename>`
- If applicable, add a line to the [unreleased] part of CHANGELOG.md, following [keep-a-changelog](https://keepachangelog.com/en/1.0.0/).

Then, please fill in below:

**Context (if applicable):**
#86 

**Description of the change:**
- Add `Cluster` class to define extracted cluster.
- Add function `extract_clusters_from_graph` which will extract GHZ and linear clusters from `graphix.GraphState`.

**Related issue:**
Related to #86 

also see that checks (github actions) pass.
If lint check keeps failing, try installing black==22.8.0 as behavior seems to vary across versions.

### CODE REVIEW

**Comment by shinich1** [comment]
@king-p3nguin could you add API docs?

**Comment by shinich1** [comment]
Perhaps an example too?

**Comment by shinich1** [comment]
do we want to mention fusion-based QC ref or something similar in the docstring?

**Comment by king-p3nguin** [comment]
I made the following changes:
- Previous extraction algorithm did not consider isolated nodes in the graph state as a cluster. Now it does.
- Added API docs
- Added an example
- Mentioned [1] for the definition of fusion in the example.
[1] Daniel E. Browne and Terry Rudolph. Resource-efficient linear optical quantum computation. Physical Review Letters, 95(1):010501, 2005.

**Comment by king-p3nguin** [comment]
I also modified some docs to resolve sphinx errors.

**Review by shinich1 — APPROVED** [review]

**Comment by shinich1** [comment]
@king-p3nguin looks good to me, please squash and merge! let's use commit message `fusion network extraction for graph state generation (#87)`.
after this is merged, I will change some names e.g. `extract_clusters_from_graph` because cluster state sounds like it's larger and extract_fusion_network may make more sense. what do you think?

**Comment by king-p3nguin** [comment]
@shinich1 Thank you for reviewing! I will merge this now.
Come to think of it, as you mentioned, the word "cluster" may create confusion by making people think of cluster states rather than mini clusters in the graph state. Maybe `get_fusion_network` or `get_fusion_network_from_graph_state` will be nicer, since the size of the fusion network is similar to the graph state.

**Comment by shinich1** [comment]
@king-p3nguin your suggestions look good! I will make these changes and get new release out soon, so that we can put the new version in the graphix-Perceval's requirements.

**Pull request merged**
